openapi: 3.0.0
info:
  title: 06-jobs-api
  version: "1.0.0"
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/NickNyamu/JobsApi/1.0.0
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - default
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Donald Duck
                email: DonaldDuck@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - default
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: peterKamau@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - default
      summary: Create Jobs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: Huawei
                position: Network Admin
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Get All Jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /jobs/:id:
    get:
      tags:
        - default
      summary: Get  Single Job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: Update Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: Huawei
                position: Network Administrator
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Job
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}